version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 6603:3306
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=rootroot
    volumes:
      - /storage/docker/mysql_data:/var/lib/mysql 

  nodewebapp:
    depends_on:
      - mysql
    build: 
      context: ./  
    container_name: node-web-app
    command: node server.js
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    links:
      - mysql:mysql
    restart: always
 
volumes:
  mysql_data:
 
networks:
  nodewebapp_mysql_net:
    driver: bridge
