version: '3.4'

# Mysql host connection details need to be configured inside the secrets file and set to node app configs.   
# '%' is a wildcard with allows any ip address can be replaced with specific ip address  
# GRANT ALL ON database.* TO 'user'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
# FLUSH PRIVILEGES; 
# EXIT;
# to check the applied permissions
# SELECT * from information_schema.user_privileges where grantee like "'user'@'%'";

services:
  nodeapp:
    image: mithilmnjrkr/nodeapp
    env_file:
      - .env
    environment: 
      - MYSQL_ROOT_HOST_FILE=/run/secrets/mysql_root_host
      - MYSQL_PORT=3306
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
    labels:
      - "Dragsters Node Backend Swarm Instance for WebPortal."
    command:
      - node /home/DragsterBackendApp/bin/start
    networks:
      - dragsters_overlay_net
    ports:
      - 3000:5000  
    volumes:
      - web_portal_logs:/home/DragsterBackendApp/log
    deploy:
      mode: replicated 
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 0s
        window: 120s
    secrets:                                                                  
      - mysql_root_host
      - mysql_user
      - mysql_password
      - mysql_database

  ngrok:
    image: wernight/ngrok
    labels:
      - "Dragsters Ngrok Swarm Instance for NodeApp Https Access."
    networks:
      - dragsters_overlay_net
    ports:
      - 4040:4040  
    command: "ngrok http nodeapp:5000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 0s
        window: 120s


  jenkins:
    image: jenkins
    labels:
      - "Dragsters Jenkins Swarm Instance for CI/CD."
    ports:
       - 8090:8080
       - 50000:50000
    networks:
       - dragsters_overlay_net
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - jenkins_home:/var/jenkins_home        
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 0s
        window: 120s
        
volumes:
  web_portal_logs:
  jenkins_home: 
 
networks:
  dragsters_overlay_net:
    driver: overlay
    

secrets: 
  mysql_root_host:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true
  mysql_database:
    external: true    
    
# Create secrets with below syntax
# echo "secret" | docker secret create secret_name -
# Put secret after echo and give the secret name as passed in environment variable files above.

