version: '3.4'

# Mysql host connection details need to be configured inside the secrets file and set to node app configs.   
# '%' is a wildcard with allows any ip address can be replaced with specific ip address  
# GRANT ALL ON database.* TO 'user'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
# FLUSH PRIVILEGES; 
# EXIT;
# to check the applied permissions
# SELECT * from information_schema.user_privileges where grantee like "'user'@'%'";

services:
  nodeapp:
    image: mithilmnjrkr/nodeapp
    env_file:
      - .env
    environment: 
      - MYSQL_ROOT_HOST_FILE=/run/secrets/mysql_root_host
      - MYSQL_PORT=3306
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
    labels:
      - "Dragsters Node Backend Swarm Instance for WebPortal."
    networks:
      - dragsters_overlay_net
    ports:
      - 3000:5000  
    command:  node ./bin/start  
    volumes:
      - web_portal_logs:/home/DragsterBackendApp/log
    deploy:
      mode: replicated 
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 0s
        window: 120s
    secrets:                                                                  
      - mysql_root_host
      - mysql_user
      - mysql_password
      - mysql_database

  ngrok:
    image: wernight/ngrok
    labels:
      - "Dragsters Ngrok Backend Swarm Instance for Https Access."
    networks:
      - dragsters_overlay_net
    ports:
      - 4040:4040  
    command: "ngrok http nodeapp:5000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 0s
        window: 120s

  visualizer:
    image: dockersamples/visualizer:stable
    networks:
        - dragsters_overlay_net
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager1]

  jenkins:
    image: jenkins
    hostname: jenkins
    environment:
        - JENKINS_OPTS='--prefix=/jenkins'
    networks:
      - dragsters_overlay_net
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - jenkins_home:/var/jenkins_home
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 0s
        window: 120s
      placement:
        constraints: [node.role == manager1]
        
        
volumes:
  web_portal_logs:
  jenkins_home:  

networks:
  dragsters_overlay_net:
    driver: overlay
    attachable: true

secrets: 
  mysql_root_host:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true
  mysql_database:
    external: true 
    
# Create secrets with below syntax
# echo "secret" | docker secret create secret_name -
# Put secret after echo and give the secret name as passed in environment variable files above.
