version: '3'

# Setup mysql database onh local and pass ip and credentials from production.env file.
# '%' is a wildcard with allows any ip address can be replaced with specific ip address . 
# GRANT ALL ON database.* TO 'user'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
# FLUSH PRIVILEGES; 
# EXIT;
# to check the applied permissions.
# SELECT * from information_schema.user_privileges where grantee like "'user'@'%'";

services: 
  nodeapp:
    image: nodeapp
    container_name: nodeapp
    #Sets the mysql port that need to be exposed as per (machine port : container port).
    ports:
      - 3000:5000
    #Sets environment variables required for the container in the production.env file
    env_file:
      - production.env   
    #Sets the volume as per (src : dest) ,src can be any location in the users/remote machine ,logs can be persisted at this location.
    volumes:
      - web_portal_logs:/home/DragsterBackendApp/log
    #On container startup for node app following command will be executed(in this case the command toi startup the app is executed)
    command: node ./bin/start  
    restart: always
volumes:
  #Mount volumes for the node app logs.
  web_portal_logs: 
#Creates the default bridge network {appname}_default and add the services to it.
#networks:

