version: '3.4'

# These details need to be configured inside the secrets file and set to node app configs.   
# '%' is a wildcard with allows any ip address can be replaced with specific ip address  
# GRANT ALL ON database.* TO 'user'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
# FLUSH PRIVILEGES; 
# EXIT;
# to check the applied permissions
# SELECT * from information_schema.user_privileges where grantee like "'user'@'%'";

services:
  nodeapp:
    image: nodeapp
    env_file:
      - .env
    labels:
      - "Dragsters Node Backend Swarm Instance for WebPortal."
    networks:
      - dragsters_overlay_net
    ports:
      - 3000:5000  
    command: node ./bin/start  
    volumes:
      - web_portal_logs:/home/DragsterBackendApp/log
    deploy:
      mode: replicated 
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 0s
        window: 120s
    secrets:                                                                  
      - mysql_credentials    

  ngrok:
    image: wernight/ngrok
    labels:
      - "Dragsters Ngrok Backend Swarm Instance for Https Access."
    networks:
      - dragsters_overlay_net
    ports:
      - 4040:4040  
    command: "ngrok http nodeapp:5000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 0s
        window: 120s

volumes:
  web_portal_logs:

networks:
  dragsters_overlay_net:
    driver: overlay
    driver_opts:
      encrypted: "true"
                                                                                                                               
secrets:                                                                      
    mysql_credentials: 
        file: ./mysql_credentials                                                                
        external: True                                                        
# Code that supports secrets to pick up in node app (keep them git ignored)
# const mysql_credentials = fs.readFileSync('/run/secrets/mysql_credentials', 'utf8').trim(); 
